### ISSUE TITLE
Find HUB with TLS WebSockets capability

### ISSUE THREAD

**Issue by yoursunny** [named-data/ndn-fch#1]
While NDN-FCH is useful for finding the nearest router, not every router has the same capability. For example, only a subset of testbed routers has the capability of accepting WebSockets connections over TLS.
NDN-FCH should accept an additional `?cap=ws-tls` parameter. When this parameter is specified, the result should only contain routers with TLS WebSockets capability.
WU-ARL/ndnmap#1 is needed to provide input for this feature.

**Comment by jdehart1** [comment]
I have added ws-tls to the ndnmap geocode.json file and marked UCLA, WU and ARIZONA as true.
All other nodes are false.

I have also set up TLS support on all the other nodes that have a FQDN. I will next ask the operators
to get port 443 open to Testbed nodes.  

Then all the other nodes that do not have a FQDN, I’ll work on the operators to see if we can get
that set up at their sites.
