### ISSUE TITLE
HTTPS deployment and CORS

### ISSUE THREAD

**Issue by yoursunny** [named-data/ndn-fch#2]
For a JavaScript web application to query NDN-FCH service and find a router with TLS WebSockets capability (to be provided in #1):
* NDN-FCH shall be deployed on an HTTPS web server, so that it can be accessed from a web application served over HTTPS.
* NDN-FCH web server shall enable Cross-Origin Resource Sharing by returning `Access-Control-Allow-Origin: *` HTTP header, so that the response is visible to the web application from another domain.

**Comment by cawka** [comment]
This issue is more appropriate for https://redmine.named-data.net/projects/named-data-net/issues.  In any case, it is done.
